### PR TITLE
Add JavaScript to test NodeJS 

### PR DESCRIPTION
**Pull request by akondas**

### CODE REVIEW

**Comment by syntheticminds** [comment]
Great stuff! Thanks for this. I'm getting performance that is similar to HHVM. I wonder where PHP will stand if/when it gets an official JIT compiler.

The `all.sh` doesn't like the php7dev Vagrant box. It doesn't have the `php5.6` command like Ubuntu so you need to switch PHP versions with the `newphp` command first like in the readme. Also, the script assumes `Iris.java` has already been compiled.

**Comment by akondas** [comment]
Thanks, in that case it would be better to remove this `all.sh` ?

**Comment by syntheticminds** [comment]
Yeah. It would be a helpful edition so I'll rewrite it when I find time. Thanks again.

**Comment by akondas** [comment]
Now it should be ok.

**Comment by syntheticminds** [comment]
Cheers!

**Pull request merged**
